---
title: "PersonalActivity"
author: "R Chellaton"
date: "11/2/2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
### load data
```{r}
library(tidyverse)
library(dplyr)
```
```{r read CSV datafiles & convert date strings to dates }
PAdata <- read.csv("activity.csv", stringsAsFactors = FALSE)
PAdata$date <- as.Date(PAdata$date, "%Y-%m-%d")
summary(PAdata)
```

### group by date & summarize
```{r Group by and Summarize}
PAdata_bg <- group_by(PAdata, date)
PAdata_summary <- summarize(PAdata_bg, totalSteps=sum(steps, na.rm=TRUE))
```

### plot histogram
```{r Plot Histogram}
p <- ggplot(PAdata_summary, aes(x=date, y=totalSteps))+
    geom_bar(stat="identity", color="dark blue", fill="light blue")
print(p)
```

### Summarize data grouped by date to get mean and median
```{r Summarize for Means and Medians}
s1 <- summarize(PAdata_bg, mean(steps, na.rm=TRUE), median(steps, na.rm=TRUE))
names(s1) <- c("date", "means", "medians")
print(s1)
```
### Plot time series of averages
```{r Plot time series of averages}
p2 <- ggplot(s1, aes(x=date, y=means, na.rm=TRUE )) + geom_bar(stat="identity", color="dark blue", fill="steelblue4")
print(p2)
```

### the 5-minute interval with the maximum number of steps
```{r get 5-minute interval with maximum steps}
s2 <- aggregate(steps ~ date, PAdata_bg, max)
s2 <- merge(s2, PAdata_bg)
print(mean(s2$interval))
```

### impute for NA values
``` {r handling NA values - find number of NAs}
totalNA <- sum(complete.cases(PAdata))
print(totalNA)
```

``` {r strategy to substitute NA values}
averageSteps <- aggregate(steps ~ interval, PAdata, FUN=mean)
newSet <- numeric()
for (i in 1:nrow(PAdata)) {
  if(is.na(PAdata[i,]$steps)) {
    steps <- subset(averageSteps, interval == PAdata[i,]$interval)$steps
  }
  else
  {
    steps <- PAdata[i,]$steps
  }
  newSet <- c(newSet, steps)
}
```

``` {r create new dataset with NAs substituted}
PAdata_new <- PAdata
PAdata_new$steps <- newSet
```

```{r plot after removing NAs}
# Histogram of total steps each day after imputing missing data
PAdata_new_summ <- PAdata_new %>% group_by(date) %>% summarize(sum=sum(steps))
PAdata_newplot <- ggplot(PAdata_new_summ, aes(x=date, y=sum)) + 
  geom_bar(stat="identity",color="dark blue", fill="steelblue") + 
  ylab("totalSteps by day - no NAs")
print(PAdata_newplot)
```

### Panel Graph for weekday and weekend average steps by Interval
```{r}
library(gridExtra)
PAdata_int <- PAdata %>% mutate(Weekday=ifelse(weekdays(date)=="Saturday" |
                                                 weekdays(date)=="Sunday",0,1))
PAdata_summ <- PAdata_int %>% 
  group_by(interval, Weekday) %>% 
  summarize(AverageSteps=mean(steps, na.rm=TRUE))
wkdayPlot <- ggplot(filter(PAdata_summ,Weekday==1),aes(x=interval, y=AverageSteps))+
                      geom_line(col="dark blue")+ylab("Weekday Average Steps")
wkendPlot <- ggplot(filter(PAdata_summ,Weekday==0),aes(x=interval, y=AverageSteps))+
                      geom_line(col="dark red")+ylab("Weekend Average Steps")
```

``` {r panel plot}
grid.arrange(wkdayPlot, wkendPlot, nrow=2)
```

