---
title: "PersonalActivity"
author: "R Chellaton"
date: "11/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
### load data
```{r}
library(tidyverse)
```
```{r read CSV datafiles & convert date strings to dates }
PAdata <- read.csv("activity.csv", stringsAsFactors = FALSE)
PAdata$date <- as.Date(PAdata$date, "%Y-%m-%d")
summary(PAdata)
```

### group by date & summarize
```{r Group by and Summarize}
PAdata_bg <- group_by(PAdata, date)
PAdata_summary <- summarize(PAdata_bg, totalSteps=sum(steps, na.rm=TRUE))
```

### plot histogram
```{r Plot Histogram}
p <- ggplot(PAdata_summary, aes(x=date, y=totalSteps))+
    geom_bar(stat="identity", color="dark blue", fill="light blue")
print(p)
```

### Summarize data grouped by date to get mean and median
```{r Summarize for Means and Medians}
s1 <- summarize(PAdata_bg, mean(steps, na.rm=TRUE), median(steps, na.rm=TRUE))
names(s1) <- c("date", "means", "medians")
print(s1)
```
### Plot time series of averages
```{r Plot time series of averages}
p2 <- ggplot(s1, aes(x=date, y=means, na.rm=TRUE )) + geom_bar(stat="identity", color="dark blue", fill="steelblue4")
print(p2)
```

### the 5-minute interval with the maximum number of steps
```{r get 5-minute interval with maximum steps}
s2 <- aggregate(steps ~ date, PAdata_bg, max)
s2 <- merge(s2, PAdata_bg)
print(mean(s2$interval))
```

### impute for NA values
```{r}
library(Amelia)
amelia.fit <- amelia(PAdata, m=5, bound=matrix(c(1,0,200), nrow=1))
PAdata_impute <- amelia.fit$imputations[[5]]
PAdata_impute_gb <- PAdata_impute %>% group_by(date)
PAdata_impute_aggr <- summarize(PAdata_impute_gb, totalSteps=sum(steps))
p <- ggplot(PAdata_impute_aggr, aes(x=date, y=totalSteps)) + 
  geom_bar(stat="identity", fill="green3", color="dark green")
print(p)
```

### Panel Graph for weekday and weekend average steps by Interval
```{r}
library(gridExtra)
PAdata_int <- PAdata %>% mutate(Weekday=ifelse(weekdays(date)=="Saturday" |
                                                 weekdays(date)=="Sunday",0,1))
PAdata_summ <- PAdata_int %>% 
  group_by(interval, Weekday) %>% 
  summarize(AverageSteps=mean(steps, na.rm=TRUE))
wkdayPlot <- ggplot(filter(PAdata_summ,Weekday==1),aes(x=interval, y=AverageSteps))+
                      geom_line(col="dark blue")+ylab("Weekday Average Steps")
wkendPlot <- ggplot(filter(PAdata_summ,Weekday==0),aes(x=interval, y=AverageSteps))+
                      geom_line(col="dark red")+ylab("Weekend Average Steps")
grid.arrange(wkdayPlot, wkendPlot, nrow=2)
```

